# Generated by Django 4.2.3 on 2023-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('UA', 'Ukrainian'), ('EN', 'English')], max_length=3),
        ),
    ]
