# Generated by Django 4.2.3 on 2023-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_userword_user_userword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='learned_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('UA', 'Ukrainian'), ('EN', 'English')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
