# Generated by Django 4.2.3 on 2023-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_userword_learned_at_alter_word_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='learned_at',
            field=models.DateField(null=True),
        ),
    ]
