# Generated by Django 4.2.3 on 2023-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_alter_userword_learned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='learned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
