# Generated by Django 4.2.3 on 2023-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_alter_userword_learned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], max_length=2),
        ),
    ]
