# Generated by Django 4.2.3 on 2023-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_alter_word_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/'),
        ),
    ]
