# Generated by Django 4.2.3 on 2023-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_alter_word_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, to='platforms.tag'),
        ),
    ]
