# Generated by Django 4.2.5 on 2023-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0011_tag_word_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="words", to="platforms.tag"),
        ),
    ]
